FROM bde2020/hadoop-resourcemanager:1.1.0-hadoop2.7.1-java8
MAINTAINER Vladimir Indjic <vladaindjic@uns.ac.rs>

RUN apt update
RUN apt install python -y

RUN curl -LO http://mirror.vorboss.net/apache/pig/pig-0.17.0/pig-0.17.0.tar.gz
RUN tar xzf pig-0.17.0.tar.gz

ENV PATH $PATH:/pig-0.17.0/bin